name: Electron CI with electron-builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS 16
        uses: actions/setup-node@v3
        with:
            node-version: '16'
      - name: Install required packages
        run: npm i
      - name: Build with electron-builder
        run: npm run build
